[languages]
sql = ["sql-formatter -c /home/viceav/.config/formatters/sql/sql.json"]
lua = [ "stylua" ]
python = [ "yapf" ]
javascript = [ "deno_fmt" ]
json = [ "deno_fmt" ]
css = [ "prettier" ]
html = [ "prettier" ]
cpp = [ "clang-format" ]
