[languages]
sql = ["sql-formatter"]
lua = [ "stylua" ]
python = [ "yapf", "isort" ]
javascript = [ "deno_fmt" ]
json = [ "deno_fmt" ]
css = [ "prettier" ]
html = [ "prettier" ]
cpp = [ "clang-format" ]
