auth {
  fingerprint {
    enabled = true
  }
}

general {
  hide_cursor = true
  ignore_empty_input = true
}

animations {
  enabled = false
}

background {
  path = $HOME/.config/hypr/Wallpapers/lock-screen.png
}

label {
  text = $TIME
  color = rgba(80, 140, 180, 1.0)
  font_size = 125
  font_family = Nimbus Roman

  shadow_passes = 3
  shadow_size = 3
  shadow_color = rgba(180, 75, 95, 1.0)
  shadow_boost = 1.5

  position = 0, -5%
  halign = right
  valign = bottom
}
